# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-GUIRobot
version:      0.04
version_from: lib/Win32/GUIRobot.pm
installdirs:  site
requires:
    Prima:                         1
    Time::HiRes:                   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
